config/routes.rb
Rails.application.routes.draw do

  mount Redactor3Rails::Engine => '/redactor3_rails'

  root 'pages#show'

  resources :pages, :only => [ :show ] do
    resources :articles, :only => [ :show ]
  end

  resources :by_titles,   :only => [ :show   ]
  resource  :user_emails, :only => [ :create ]

  namespace :admin, :path => 'hcms' do
    root 'pages#index'

    resources :pages do
      resources :articles
    end

    resources :move_pages, :only => [ :update ]

    devise_for :users
  end

end

app/views/admin/pages/_actions.html.erb
<%
  # Render with:
  #
  #   render :partial => 'actions', :locals => {
  #     :page => Page model instance
  #   }
-%>
<td>
  <% if page.first? -%>
    &nbsp;
  <% else -%>
    <%= form_for( page, :url => admin_move_page_path( page ) ) do | f | %>
    <%= f.submit( '↑', :name => 'higher' ) %>
    <% end -%>
  <% end -%>
</td>
<td>
  <% if page.last? -%>
    &nbsp;
  <% else -%>
    <%= form_for( page, :url => admin_move_page_path( page ) ) do | f | %>
    <%= f.submit( '↓', :name => 'lower' ) %>
    <% end -%>
  <% end -%>
</td>
<td><%= link_to 'Show',    [        :admin, page ] %></td>
<td><%= link_to 'Edit',    [ :edit, :admin, page ] %></td>
<td><%= link_to 'Destroy', [        :admin, page ], method: :delete, data: { confirm: apphelp_destroy_confirm(page) } %></td>

app/views/admin/pages/_form.html.erb
<%= form_for( [ :admin, @page ] ) do | f | %>
  <% if @page.errors.any? -%>
    <div id="error_explanation">
      <h3><%= pluralize( @page.errors.count, "error" ) %> prevented the page from being saved:</h3>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end -%>

  <div class="field">
    <p>
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </p>
  </div>

  <div class="field">
    <p>
      <%= f.label :slug %>
      <small>
        <%= @page.persisted? ? '(beware if changing this; people may have bookmarked this page using its old slug)' : '(optional; if omitted, the slug is generated from the page title)' %>
      </small>
      <br />
      <%= f.text_field :slug %>
    </p>
  </div>

  <% if Page.top_level.count > 0 -%>
    <div class="field">
      <p>
        <%= f.label :page_id %><br />
        <%= f.collection_select :page_id,
                                Page.top_level_except( @page ),
                                :id,
                                :title,
                                :include_blank => 'Do not put into a menu' %>
      </p>
    </div>
  <% end -%>

  <div class="field">
    <p>
      <%= f.label :page_type %><br />
      <%= f.collection_select :page_type, ::Page::PAGE_TYPES, :internal_type, :human_text %><br />
      <small><em>You must save then re-edit the page if you change this setting</em></small><br />
    </p>
  </div>

  <div id="non-blog-fields" style="display: <%= @page.is_blog_type? ? 'none' : 'block' %>">
    <div class="field">
      <%= f.check_box :hidden %> <%= f.label :hidden %>
    </div>

    <div class="field">
      <%= f.check_box :raw_editor %> <%= f.label :raw_editor %><br />
      &nbsp;&nbsp;&nbsp;&nbsp;<small><em>You must save then re-edit the page if you change this setting</em></small>
    </div>

    <% if @page.is_form_type? -%>
      <p>
        In the editing area below, just type in any page contents you want <i>above</i> the main form itself. The form on the finished page will always have the same contents - name, contact information and so-on. Currently, you can't edit that section.
      </p>
    <% else -%>
      <p></p>
    <% end -%>

    <% if @page.raw_editor -%>
      <div class="redactor_container">
        <div class="redactor-box redactor-styles-on">
          <%= f.text_area :body, :class => 'not_redactor', :rows => 40, :cols => 120 %>
        </div>
      </div>
    <% else -%>
      <div class="redactor_container">
        <div id="redactor_toolbar"></div>
        <%= f.text_area :body, :class => 'custom_redactor', :rows => 40, :cols => 120 %>
      </div>
    <% end -%>

    <% if @page.is_form_type? -%>
      <div class="field">
        <p>
          <%= f.label :form_selection_list_contents, 'Below, you can type in an optional list of selectable items to show in a drop-down menu as part of the form. Add one per line. If left empty, no such menu is offered:' %><br />
          <%= f.text_area :form_selection_list_contents, :rows => 8, :cols => 80 %>
        </p>
      </div>
    <% end -%>
  </div>

  <div class="actions">
    <p>
      <%= f.submit %>
    </p>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @page] %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<h1>All pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th class="centre" colspan="2">Move</th>
      <th class="centre" colspan="3">Actions</th>
      <th class="centre">In navigation bar?</th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do | page | -%>

      <tr class="<%= cycle( 'even', 'odd' ) %>">
        <td><%= page.title %></td>
          <%= render :partial => 'actions', :locals => { :page => page } %>
        <td class="centre"><%= page.hidden? ? '<b>No</b>'.html_safe : 'Yes' %>
      </tr>

      <% page.children.each do | child_page | -%>

        <tr class="children <%= cycle( 'even', 'odd' ) %>">
          <td>&mdash; <%= child_page.title %></td>
            <%= render :partial => 'actions', :locals => { :page => child_page } %>
          <td class="centre"><%= child_page.hidden? ? '<b>No</b>'.html_safe : 'Yes' %>
        </tr>

      <% end -%>
    <% end -%>
  </tbody>
</table>

<br>

<%= link_to 'New page', new_admin_page_path %>

app/views/admin/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/show.html.erb
<%= render :partial => 'shared/page', :locals => { :page => @page } %>