config/routes.rb
Rails.application.routes.draw do

  mount Redactor3Rails::Engine => '/redactor3_rails'

  root 'pages#show'

  resources :pages, :only => [ :show ] do
    resources :articles, :only => [ :show ]
  end

  resources :by_titles,   :only => [ :show   ]
  resource  :user_emails, :only => [ :create ]

  namespace :admin, :path => 'hcms' do
    root 'pages#index'

    resources :pages do
      resources :articles
    end

    resources :move_pages, :only => [ :update ]

    devise_for :users
  end

end

app/models/article.rb
# A blog article. Attached to Pages of type "blog".
#
class Article < ActsLikePage

  mount_uploader :article_hero_image, ArticleHeroImageUploader

  belongs_to :page
  default_scope -> { order( :created_at => :desc ) }

  before_validation do
    generate_unique_slug() if self.slug.blank? # see ApplicationRecord
  end

  validates_presence_of :title, :slug, :article_hero_image, :summary, :body
  validates_uniqueness_of :slug

  def is_article?
    true
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController

  layout :determine_layout

  # Via Devise
  before_action :authenticate_admin_user!
  before_action :set_page
  before_action :set_article, only: [ :show, :edit, :update, :destroy ]

  public

    # GET /admin/pages/<page_id>/articles
    def index
      @articles = Article.where(page_id: @page.id)
    end

    # GET /admin/pages/<page_id>/articles/<id>
    def show
    end

    # GET /admin/pages/<page_id>/articles/new
    def new
      @article = Article.new(page_id: @page.id)
    end

    # GET /admin/pages/<page_id>/articles/edit/<id>
    def edit
    end

    # POST /admin/pages/<page_id>/articles
    def create
      @article         = Article.new( article_params )
      @article.page_id = @page.id

      respond_to do | format |
        if @article.save
          format.html do
            redirect_to(
              admin_page_article_url( page_id: @page.id, id: @article.id ),
              notice: 'Article was successfully created.'
            )
          end
        else
          format.html { render :new }
        end
      end
    end

    # PATCH/PUT //admin/pages/<page_id>/articles/<id>
    def update
      respond_to do | format |
        if @article.update( article_params )
          if @article.previous_changes.has_key?( 'raw_editor' )
            format.html do
              redirect_to(
                edit_admin_page_article_url( page_id: @page.id, id: @article.id ),
                notice: 'Editing style changed.'
              )
            end
          else
            format.html do
              redirect_to(
                admin_page_article_url( page_id: @page.id, id: @article.id ),
                notice: 'Article was successfully updated.'
              )
            end
          end
        else
          format.html { render :edit }
        end
      end
    end

    # DELETE /admin/pages/<page_id>/articles/<id>
    def destroy
      @article.destroy

      respond_to do | format |
        format.html do
          redirect_to(
            admin_page_articles_url( page_id: @page.id ),
            notice: 'Article was successfully destroyed.'
          )
        end
      end
    end

  private

    def determine_layout
      case action_name
        when 'show'
          'articles'
        else
          'admin'
      end
    end

    def set_page
      @page = Page.find_by_id_or_slug!( params[ :page_id ] )
    end

    def set_article
      @article = Article.find_by_id_or_slug!( params[ :id ] )
    end

    def article_params
      params.require( :article ).permit( :title,
                                         :slug,
                                         :article_hero_image,
                                         :summary,
                                         :body,
                                         :raw_editor )
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  layout 'articles'

  def show
    @page    =    Page.find_by_id_or_slug!( params[ :page_id ] )
    @article = Article.find_by_id_or_slug!( params[ :id      ] )
  end
end

app/views/admin/articles/_actions.html.erb
<%
  # Render with:
  #
  #   render :partial => 'actions', :locals => {
  #     :article => Article model instance
  #   }
  #
  page_id = article.page.id
-%>

<td><%= link_to 'Show',         admin_page_article_path( page_id: page_id, id: article.id ) %></td>
<td><%= link_to 'Edit',    edit_admin_page_article_path( page_id: page_id, id: article.id ) %></td>
<td><%= link_to 'Destroy',      admin_page_article_path( page_id: page_id, id: article.id ), method: :delete, data: { confirm: apphelp_destroy_confirm(article) } %></td>

app/views/admin/articles/_form.html.erb
<%= form_for( [ :admin, @page, @article ] ) do | f | %>
  <% if @article.errors.any? -%>
    <div id="error_explanation">
      <h3><%= pluralize(@article.errors.count, "error") %> prevented the article from being saved:</h3>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end -%>

  <div class="field">
    <p>
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </p>
  </div>

  <div class="field">
    <p>
      <%= f.label :article_hero_image %><br />
      <%= f.file_field :article_hero_image %>
      <% if @page.persisted? -%>
        <br><small><em>You only need to choose an image if changing the one that's already attached to the article</em></small>
      <% end -%>
    </p>
  </div>

  <div class="field">
    <p>
      <%= f.label :summary %><br />
      <%= f.text_area :summary, cols: '60', rows: '5' %><br />
      <small><em>This is a brief, plain text (no styling) summary used in the list of blog articles</em></small>
    </p>
  </div>

  <div class="field">
    <%= f.check_box :raw_editor %> <%= f.label :raw_editor %><br />
    &nbsp;&nbsp;&nbsp;&nbsp;<small><em>You must save then re-edit the article if you change this setting</em></small>
  </div>

  <div class="field">
    <p>
      <%= f.label :body %><br />
    </p>
  </div>

  <% if @article.raw_editor -%>
    <div class="redactor_container">
      <div class="redactor-box redactor-styles-on">
        <%= f.text_area :body, :class => 'not_redactor', :rows => 40, :cols => 120 %>
      </div>
    </div>
  <% else -%>
    <div class="redactor_container">
      <div id="redactor_toolbar"></div>
      <%= f.text_area :body, :class => 'custom_redactor', :rows => 40, :cols => 120 %>
    </div>
  <% end -%>

  <div class="actions">
    <p>
      <%= f.submit %>
    </p>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_page_article_path(page_id: @page.id, id: @article.id) %> |
<%= link_to 'Back', admin_page_articles_path(page_id: @page.id) %>

app/views/admin/articles/index.html.erb
<h1>All articles for blog "<%= @page.title %>"</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th class="centre" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
<% @articles.each do | article | -%>
      <tr class="<%= cycle( 'even', 'odd' ) %>">
        <td><%= article.title %></td>
        <%= render :partial => 'actions', :locals => { :article => article } %>
      </tr>
<% end -%>
  </tbody>
</table>

<br>

<%= link_to 'New blog article', new_admin_page_article_path() %> |
<%= link_to 'Visit blog page', [ :admin, @page ] %>

app/views/admin/articles/new.html.erb
<h1>Write new article</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_pages_path %>

app/views/admin/articles/show.html.erb
<%= render :partial => 'shared/article', :locals => { :article => @article } %>