config/routes.rb
Rails.application.routes.draw do

  mount Redactor3Rails::Engine => '/redactor3_rails'

  root 'pages#show'

  resources :pages, :only => [ :show ] do
    resources :articles, :only => [ :show ]
  end

  resources :by_titles,   :only => [ :show   ]
  resource  :user_emails, :only => [ :create ]

  namespace :admin, :path => 'hcms' do
    root 'pages#index'

    resources :pages do
      resources :articles
    end

    resources :move_pages, :only => [ :update ]

    devise_for :users
  end

end

app/views/shared/_article.html.erb
<%
  # Ensure a local "article" is set to the Article instance to render:
  #
  #   render :partial => 'shared/article', :locals => { :article => ... }
-%>
<article class="article">
  <div class='blog-header'>
    <div class="article-date-and-heading-container">
      <h2 class="article-heading"><%= article.title %></h2>
      <div class="article-date"><%= apphelp_human_time(article.created_at) %></div>
    </div>
    <div class="article-summary"><%= article.summary %></div>
  </div>

  <p>
    <img class="article-hero-imag" src="<%= article.article_hero_image.url %>" alt="<%= article.title %>">
  </p>

  <%= article.body.html_safe() %>
</article>

app/views/shared/_page.html.erb
<%
  # Ensure a local "page" is set to the Page / AdminPage instance to render:
  #
  #   render :partial => 'shared/page', :locals => { :page => ... }
-%>
<% if page.is_blog_type? -%>

  <% if page.articles.any? -%>
    <section class="blog-articles">
      <% page.articles.each do | article | %>
        <article class="article">
          <%= link_to page_article_path(page_id: page.id, id: article.id), class: 'article-link' do %>
            <img class="article-hero-image" src="<%= article.article_hero_image.url %>" alt="<%= article.title %>">
            <div class="article-date-and-heading-container">
              <h4 class="article-heading"><%= article.title %></h4>
              <div class="article-date"><%= apphelp_human_time(article.created_at) %></div>
            </div>
            <div class="article-summary"><%= article.summary %></div>
          <% end -%>
        </article>
      <% end -%>
    </section>
  <% else -%>
    No articles have been written for this blog yet.
    <%= link_to 'Write one now!', new_admin_page_article_path(page_id: page.id) %>
  <% end -%>

<% elsif page.is_form_type? -%>

  <%= page.body.html_safe() %>

  <%= form_tag( user_emails_path ) do %>
    <p>
      <%= label_tag :name, 'Your name' %><br>
      <%= text_field_tag :name, nil, :placeholder =>'Name' %>
    </p>
    <p>
      <%= label_tag :email, 'Your e-mail address' %><br>
      <%= email_field_tag :email, nil, :placeholder => 'E-mail address' %>
    </p>
    <p>
      <%= label_tag :email, 'Preferred telephone contact number' %><br>
      <%= telephone_field_tag :phone, nil, :placeholder => 'Telephone number' %>
    </p>
    <% if page.page_type == Page::PAGE_TYPE_BOOKING_FORM -%>
      <p>
        <%= label_tag :date, 'Date (at least two days in advance)' %><br>
        <%= date_field_tag :date, '', :placeholder => ( Date.today + 2.days ).strftime( '%-d %b %Y' ), :min => Date.today + 2.days %>
      </p>
      <p>
        <%= label_tag :time, 'Preferred time (10am or later)' %><br>
        <%= time_field_tag :time, '', :placeholder => '10:00', :min => Time.parse( '10:00' ), :step => 60.minutes %>
      </p>
    <% end -%>
    <% unless page.form_selection_list_contents.strip.blank? -%>
      <p>
        <%= label_tag :selection, 'Please choose an item from the list' %><br>
        <%= form_page_selection_list( page ) %><br />
      <p>
    <% end -%>
    <% if page.page_type == Page::PAGE_TYPE_BOOKING_FORM -%>
      <p>
        <%= label_tag :notes, 'Additional notes and requests' %><br>
        <%= text_area_tag :notes, '', :rows => 8, :cols => 80, :placeholder => 'List of attendees, special date/time requests, questions etc.' %>
      </p>
    <% else -%>
      <p>
        <%= label_tag :message, 'What would you like to ask?' %><br>
        <%= text_area_tag :message, '', :rows => 8, :cols => 80 %>
      </p>
    <% end -%>

    <%= recaptcha_tags() %>

    <p>
      <% if page.page_type == Page::PAGE_TYPE_BOOKING_FORM -%>
        <%= submit_tag 'Send booking information' %>
      <% else -%>
        <%= submit_tag 'Send message' %>
      <% end -%>
    </p>
  <% end -%>

<% else -%>

  <%= page.body.html_safe() %>

<% end -%>