config/routes.rb
Rails.application.routes.draw do

  mount Redactor3Rails::Engine => '/redactor3_rails'

  root 'pages#show'

  resources :pages, :only => [ :show ] do
    resources :articles, :only => [ :show ]
  end

  resources :by_titles,   :only => [ :show   ]
  resource  :user_emails, :only => [ :create ]

  namespace :admin, :path => 'hcms' do
    root 'pages#index'

    resources :pages do
      resources :articles
    end

    resources :move_pages, :only => [ :update ]

    devise_for :users
  end

end

app/views/layouts/_google_tags.html.erb
<%
  google_ad_id = ENV['GOOGLE_AD_ID']
  unless google_ad_id.blank?
-%>
<!-- Global site tag (gtag.js) - Google Ads: <%= google_ad_id %> -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-<%= google_ad_id %>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'AW-<%= google_ad_id %>');
</script>
<% end -%>

app/views/layouts/_messages.html.erb
<% if notice.present? || alert.present? -%>
      <section class="messages">
<%   if notice.present? -%>
        <p class="notice"><%= notice %></p>
<%   end -%>
<%   if alert.present? %>
        <p class="alert"><%= alert %></p>
<%   end -%>
      </section>
<% end -%>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=0.8">

    <title><%= Rails.application.config.uk_org_pond_hcms.site_name %>: Admin</title>

    <%= stylesheet_link_tag    'admin', media: 'all' %>
    <%= javascript_include_tag 'admin'               %>

    <%= csrf_meta_tags %>
    <%= render partial: 'layouts/google_tags' %>
  </head>

  <body>
    <section class="admin">
<%= render :partial => 'layouts/messages' %>
<%= yield %>
    </section>

    <footer>
<% if user_signed_in? -%>
      <%= link_to( 'Log out', destroy_admin_user_session_path, :method => :delete ) %> |
<% end -%>
      <%= link_to( 'Public site', root_path ) %>
    </footer>
  </body>
</html>

app/views/layouts/articles.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.8, viewport-fit=cover">

    <title><%= Rails.application.config.uk_org_pond_hcms.site_name %>: <%= @article.title %></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'pages', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= render partial: 'layouts/google_tags' %>
  </head>
  <body>
    <section class="header">
      <img id="logo" alt="Logo" src="<%= image_path( 'logo.png' )%>" width="<%= Rails.application.config.uk_org_pond_hcms.logo_w %>" height="<%= Rails.application.config.uk_org_pond_hcms.logo_h %>">
      <nav>
        <a target="_blank" href="<%= Rails.application.config.uk_org_pond_hcms.facebook  %>"><i class="fa fa-facebook-official"></i></a>
        <a target="_blank" href="<%= Rails.application.config.uk_org_pond_hcms.twitter   %>"><i class="fa fa-twitter-square"></i></a>
        <a target="_blank" href="<%= Rails.application.config.uk_org_pond_hcms.instagram %>"><i class="fa fa-instagram"></i></a>
      </nav>
    </section>

    <section class="main">
      <nav>
        <div class="pure-menu pure-menu-horizontal">
          <ul class="pure-menu-list">
<% Page.top_level.for_navigation.each do | page | -%>
            <li class="pure-menu-item pure-menu-allow-hover<%= page.children.for_navigation.present? ? ' pure-menu-has-children' : '' %>">
              <%= link_to( page.title, page_path( page.slug ), :class => 'pure-menu-link' ) %>
<%   if page.children.for_navigation.present? -%>
              <ul class="pure-menu-children">
<%     page.children.for_navigation.each do | child | -%>
                <li class="pure-menu-item">
                  <%= link_to( child.title, page_path( child.slug ), :class => 'pure-menu-link' ) %>
                </li>
<%     end -%>
              </ul>
<%   end -%>
            </li>
<% end -%>
          </ul>
        </div>
      </nav>

      <section class="content">
        <div class="above-clear">
<%= render :partial => 'layouts/messages' %>
<%= yield %>
        </div>
        <div style="clear: both"></div>
      </section>
    </section>

    <section class="footer">
      <section class="footer_content">
        <% if user_signed_in? -%>

          <% if @article.present? -%>
            <%= link_to 'Edit article', edit_admin_page_article_path( @page.id, id: @article.id ) %> |
          <% end -%>
          <%= link_to 'New blog article', new_admin_page_article_path() %> |
          <%= link_to 'List articles', admin_page_articles_path %> |
          <%= link_to 'New page', new_admin_page_path() %>

        <% else -%>

          <br>
          <%= link_to Rails.application.config.uk_org_pond_hcms.contact_tel_human, "tel:#{ Rails.application.config.uk_org_pond_hcms.contact_tel_full }" %> |
          <%= link_to Rails.application.config.uk_org_pond_hcms.contact_email, "mailto:#{ Rails.application.config.uk_org_pond_hcms.contact_email }" %>

        <% end -%>
      </section>
    </section>
  </body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.8, viewport-fit=cover">

    <title><%= Rails.application.config.uk_org_pond_hcms.site_name %>: <%= @page.title %></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'pages', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= render partial: 'layouts/google_tags' %>
  </head>
  <body>
    <section class="header">
      <img id="logo" alt="Logo" src="<%= image_path( 'logo.png' )%>" width="<%= Rails.application.config.uk_org_pond_hcms.logo_w %>" height="<%= Rails.application.config.uk_org_pond_hcms.logo_h %>">
      <nav>
        <a target="_blank" href="<%= Rails.application.config.uk_org_pond_hcms.facebook  %>"><i class="fa fa-facebook-official"></i></a>
        <a target="_blank" href="<%= Rails.application.config.uk_org_pond_hcms.twitter   %>"><i class="fa fa-twitter-square"></i></a>
        <a target="_blank" href="<%= Rails.application.config.uk_org_pond_hcms.instagram %>"><i class="fa fa-instagram"></i></a>
      </nav>
    </section>

    <section class="main">
      <nav>
        <div class="pure-menu pure-menu-horizontal">
          <ul class="pure-menu-list">
<% Page.top_level.for_navigation.each do | page | -%>
            <li class="pure-menu-item pure-menu-allow-hover<%= page.children.for_navigation.present? ? ' pure-menu-has-children' : '' %><%= page.id == @page.id || page.id == @page.page.try( :id ) ? ' current_page' : ''%>">
              <%= link_to( page.title, page_path( page.slug ), :class => 'pure-menu-link' ) %>
<%   if page.children.for_navigation.present? -%>
              <ul class="pure-menu-children">
<%     page.children.for_navigation.each do | child | -%>
                <li class="pure-menu-item">
                  <%= link_to( child.title, page_path( child.slug ), :class => 'pure-menu-link' ) %>
                </li>
<%     end -%>
              </ul>
<%   end -%>
            </li>
<% end -%>
          </ul>
        </div>
      </nav>

      <section class="content">
        <div class="above-clear">
          <%= render :partial => 'layouts/messages' %>
          <%= yield %>
        </div>
        <div style="clear: both"></div>
      </section>
    </section>

    <section class="footer">
      <section class="footer_content">
        <% if user_signed_in? -%>

          <% if @page.is_a?(Page) -%>
            <% if @page.is_blog_type? -%>
              <%= link_to 'New article', new_admin_page_article_path( page_id: @page.id ) %> |
              <%= link_to 'List articles', admin_page_articles_path( page_id: @page.id ) %> |
              <%= link_to 'Edit this page', [ :edit, :admin, @page ] %> |
            <% else -%>
              <%= link_to 'Edit', [ :edit, :admin, @page ] %> |
              <%= link_to 'New page', new_admin_page_path %> |
            <% end -%>
          <% else -%>
            <%= link_to 'New page', new_admin_page_path %> |
          <% end -%>
          <%= link_to 'List pages', admin_pages_path %>

        <% else -%>

          <br>
          <%= link_to Rails.application.config.uk_org_pond_hcms.contact_tel_human, "tel:#{ Rails.application.config.uk_org_pond_hcms.contact_tel_full }" %> |
          <%= link_to Rails.application.config.uk_org_pond_hcms.contact_email, "mailto:#{ Rails.application.config.uk_org_pond_hcms.contact_email }" %>

        <% end -%>
      </section>
    </section>
  </body>
</html>